/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sodokugame;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * @author Khuy
 */

public class MenuJFrame extends javax.swing.JFrame implements ActionListener{
    
    public SodokuFrame playGameFrame;
    HowToPlayFrame howToPlayFrame;
    AboutUs aboutUsFrame;
    
    public MenuJFrame() {
        initComponents();
        
        
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo2.jpg")));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Thêm đoạn này
         this.setSize(860, 700);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        

        this.setResizable(false);
        this.setBackground(Color.white);
        this.setTitle("Menu");
        btnPlay.setBackground(Color.white);
        btnClose.setBackground(Color.white);
        btnHowToPlay.setBackground(Color.white);
        btnAboutUs.setBackground(Color.white);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuInfo = new javax.swing.JPanel();
        btnPlay = new javax.swing.JToggleButton();
        btnClose = new javax.swing.JToggleButton();
        btnHowToPlay = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        pnlMenuInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlMenuInfo.setMaximumSize(new java.awt.Dimension(900, 900));
        pnlMenuInfo.setMinimumSize(new java.awt.Dimension(500, 500));
        pnlMenuInfo.setPreferredSize(new java.awt.Dimension(802, 681));

        btnPlay.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(0, 153, 153));
        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 153, 153));
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnHowToPlay.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnHowToPlay.setForeground(new java.awt.Color(0, 153, 153));
        btnHowToPlay.setText("HOW TO PLAY");
        btnHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHowToPlayActionPerformed(evt);
            }
        });

        btnAboutUs.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAboutUs.setForeground(new java.awt.Color(0, 153, 153));
        btnAboutUs.setText("ABOUT US");
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sodokugame/iconimage/LGOGOSUDOKU.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlMenuInfoLayout = new javax.swing.GroupLayout(pnlMenuInfo);
        pnlMenuInfo.setLayout(pnlMenuInfoLayout);
        pnlMenuInfoLayout.setHorizontalGroup(
            pnlMenuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuInfoLayout.createSequentialGroup()
                .addGroup(pnlMenuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuInfoLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(pnlMenuInfoLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addGroup(pnlMenuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnlMenuInfoLayout.setVerticalGroup(
            pnlMenuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuInfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Open Play Frame
     * @param evt 
     */
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnPlay){
            playGameFrame = new SodokuFrame();
            playGameFrame.timer.start();
            playGameFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPlayActionPerformed
    
    /**
     * Close Menu
     * @param evt 
     */
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
         
                        int reply = JOptionPane.showConfirmDialog(null, "Do you want exit game?", "Star?", JOptionPane.YES_NO_OPTION);
                        
                        if (reply == JOptionPane.YES_OPTION) {
                            JOptionPane.showMessageDialog(null, "Thank you and see you again!");
                            System.exit(0);
                        }         
    }//GEN-LAST:event_btnCloseActionPerformed
    
    /**
     * Open Tutorial Frame
     * @param evt 
     */
    private void btnHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHowToPlayActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnHowToPlay){
            howToPlayFrame = new HowToPlayFrame();
            howToPlayFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnHowToPlayActionPerformed
    
    /**
     * Open About Us Frame
     * @param evt 
     */
    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        aboutUsFrame = new AboutUs();
        aboutUsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JToggleButton btnClose;
    private javax.swing.JButton btnHowToPlay;
    private javax.swing.JToggleButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlMenuInfo;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void actionPerformed(ActionEvent e) {
    }
}
